language: node_js
sudo: required
before_script:
  - npm install -g polymer-cli
  - polymer install
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run -s '-screen 0 1024x768x24' polymer test
dist: trusty
